名字: Java CI with Maven

on:
  push:
    分支: 
      - "master"  # 仅在推送到 master 分支时运行工作流
  # pull_request:
  #   branches:
  #     - "master"  # 注释掉这一行，避免在 PR 时触发工作流

作业:
  build:
    runs-on: ubuntu-latest  # 在最新的 Ubuntu 操作系统上运行作业

    steps:
      - 名字: Checkout code
        uses: actions/checkout@v4  # 拉取代码

      - 名字: Set up JDK 1.8
        uses: actions/setup-java@v4  # 设置 JDK 环境
        with:
          java-version: '1.8'  # 设置 Java 版本为 1.8
          distribution: 'temurin'  # 使用 Temurin 发行版
          cache: maven  # 缓存 Maven 依赖，提高执行速度

      - 名字: Build with Maven
        run: mvn -B package --file pom.xml  # 使用 Maven 构建项目

      # Optional: Upload the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - 名字: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6  # 提交 Maven 依赖图
